export const BILLING_CYCLES = {
  monthly: 'monthly',
  annual: 'annual',
};

export const SUBSCRIPTION_PLANS = [
  {
    id: 'awakened',
    icon: 'Awakened',
    name: 'Awakened',
    legacyName: 'Free',
    accent: 'gold',
    monthlyPrice: 0,
    annualPrice: 0,
    badge: 'Free',
    included: [
      '1 Workout Plan Generation',
      '1 Meal Plan Generation',
      '1 Meal Scan every 10 levels',
      'Character Progression',
      'Daily Quests',
      'XP System',
      'Basic Avatar',
      'Basic Fitness Calculators',
    ],
    annualExtras: [],
  },
  {
    id: 'hunter',
    icon: 'Hunter',
    name: 'Hunter',
    legacyName: 'Basic',
    accent: 'purple',
    monthlyPrice: 4.99,
    annualPrice: 49.99,
    badge: 'Starter',
    included: ['2 Workout Plans per month', '2 Meal Plans per month', '1 AI Meal Scan per day', 'Paid Fitness Calculators', 'Image Avatar'],
    annualExtras: ['Exclusive Hunter avatar title'],
  },
  {
    id: 'shadow-elite',
    icon: 'Elite',
    name: 'Shadow Elite',
    legacyName: 'Pro',
    accent: 'purple',
    monthlyPrice: 9.99,
    annualPrice: 99.99,
    badge: 'Premium',
    included: [
      '4 Workout Plans per month',
      '4 Meal Plans per month',
      '3 AI Meal Scans per day',
      'Paid Fitness Calculators',
      'Image Avatar',
      '(coming soon)',
      'AI Body Shape Avatar',
      'Purple Premium Aura',
      'Exclusive equipment skins',
      'Priority feature access',
    ],
    annualExtras: [],
  },
  {
    id: 'monarch',
    icon: 'Monarch',
    name: 'Monarch',
    legacyName: 'Ascended',
    accent: 'gold',
    monthlyPrice: 14.99,
    annualPrice: 149.99,
    badge: 'Best Value',
    featured: true,
    included: [
      '4 Workout Plans per month',
      '4 Meal Plans per month',
      '7 AI Meal Scans per day',
      'Paid Fitness Calculators',
      'Image Avatar',
      'Monarch Badge',
      '(coming soon)',
      'AI Body Shape Avatar',
      'Animated Avatar',
      'Legendary Avatar Cosmetics',
      'VIP Priority Support',
      'Exclusive Seasonal Rewards',
    ],
    annualExtras: [],
  },
];
