export const BILLING_CYCLES = {
  monthly: 'monthly',
  annual: 'annual',
};

export const SUBSCRIPTION_PLANS = [
  {
    id: 'awakened',
    icon: 'Awakened',
    name: 'Awakened',
    legacyName: 'Free',
    accent: 'gold',
    monthlyPrice: 0,
    annualPrice: 0,
    badge: 'Free',
    included: [
      '2 Workout Plan Generations',
      '2 Meal Plan Generations',
      '1 AI Meal Scan',
      'Character Progression',
      'Daily Quests',
      'XP System',
      'Basic Avatar',
      'All Fitness Calculators',
    ],
    annualExtras: [],
  },
  {
    id: 'hunter',
    icon: 'Hunter',
    name: 'Hunter',
    legacyName: 'Basic',
    accent: 'purple',
    monthlyPrice: 4.99,
    annualPrice: 49.99,
    badge: 'Starter',
    included: ['2 Workout Plans per month', '2 Meal Plans per month', '15 AI Meal Scans per month'],
    annualExtras: ['2 months free', 'Exclusive Hunter avatar title'],
  },
  {
    id: 'shadow-elite',
    icon: 'Elite',
    name: 'Shadow Elite',
    legacyName: 'Pro',
    accent: 'purple',
    monthlyPrice: 9.99,
    annualPrice: 99.99,
    badge: 'Premium',
    included: ['4 Workout Plans per month', '4 Meal Plans per month', '30 AI Meal Scans per month'],
    annualExtras: ['2 months free', '(coming soon)', 'Purple Premium Aura', 'Exclusive equipment skins', 'Priority feature access'],
  },
  {
    id: 'monarch',
    icon: 'Monarch',
    name: 'Monarch',
    legacyName: 'Ascended',
    accent: 'gold',
    monthlyPrice: 14.99,
    annualPrice: 149.99,
    badge: 'Best Value',
    featured: true,
    included: ['4 Workout Plans per month', '4 Meal Plans per month', '110 AI Meal Scans per month'],
    annualExtras: [
      '2 months free',
      'Monarch Badge',
      '(coming soon)',
      'Legendary Avatar Cosmetics',
      'VIP Priority Support',
      'Exclusive Seasonal Rewards',
    ],
  },
];
